/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Watch(props) {
  const { nodes, materials } = useGLTF('/watch/vintage_pocket_watch_4k.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Circle001.geometry} material={materials.vintage_pocket_watch_glass} />
      <mesh geometry={nodes.Circle001_1.geometry} material={materials.vintage_pocket_watch} />
      <mesh geometry={nodes.Circle001_2.geometry} material={materials.vintage_pocket_watch_hands} />
      <mesh geometry={nodes.vintage_pocket_watch_hour_hand.geometry} material={materials.vintage_pocket_watch_hands} />
      <mesh geometry={nodes.vintage_pocket_watch_minute_hand.geometry} material={materials.vintage_pocket_watch_hands} />
      <mesh geometry={nodes.vintage_pocket_watch_second_hand.geometry} material={materials.vintage_pocket_watch_hands} />
    </group>
  )
}

useGLTF.preload('/watch/vintage_pocket_watch_4k.gltf')
